name: FOSSA license scan
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'metadata/**'
      - 'legal/**'
      - '**.md'
      - '.github/workflows/**'
      - '.github/FUNDING.yml'
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo including backpack submodule
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: '17'
        
      - name: Install FOSSA CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash"
        
      - name: Run FOSSA scan
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze
